version: "3.8"

services:
#-------------------------------------------[ NGINX ]-----------------------------------------------
  nginx:
    container_name: nginx
    image: nginx:myVersion
    build:
      context: ./requirements/nginx
    networks:
      - inception
    ports:
      - "443:443"
      - 9000
    restart: always
    volumes:
      - wpdata:/var/www/html
    depends_on:
      - wordpress

#-------------------------------------------[ MARIADB ]-----------------------------------------------
  mariadb:
    image: mariadb:myVersion
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      args:
        - MYSQL_ROOT_PASSWORD
        - MYSQL_DATABASE
        - MYSQL_USER
        - MYSQL_PASSWORD
    networks:
      - inception
    volumes:
     - dbdata:/var/lib/mysql
    ports:
      - 3306
    init: true
    restart: unless-stopped


#-------------------------------------------[ WORDPRESS ]-----------------------------------------------
  wordpress:
    container_name: wordpress
    image: wordpress:myVersion
    build:
      context: ./requirements/wordpress
    env_file:
      - .env
    networks:
      - inception
    restart: unless-stopped
    depends_on:
      - mariadb
    volumes:
      - wpdata:/var/www/html
    ports:
      - 9000
      - 3306
   
      
#-------------------------------------------[ PARAM VOLUMES AND NETWORK ]-----------------------------------------------
networks:
  inception:
    name: inception_network
    driver: bridge

volumes:
  dbdata:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/$USER/data/DB
  wpdata:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/$USER/data/WordPress
