version: "3.9"

services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    networks:
      - inception
    ports:
      - 8080:80
    restart: unless-stopped
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    networks:
      - inception
    restart: unless-stopped
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    networks:
      - inception
    restart: unless-stopped
networks:
  inception:
    name: inception_network